version: "3.6"
services:
  typescript-express-app:
    image: temp-name
    build:
       context: .
       dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes:
      - ./src:/app/src
      - /app/node_modules